# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

os: linux
dist: xenial

before_install:
- openssl aes-256-cbc -K $encrypted_42ba9e6778af_key -iv $encrypted_42ba9e6778af_iv
  -in labdevopscloud-gaby-e21d31214aba.json.enc -out ../labdevopscloud-gaby-e21d31214aba.json
  -d

jobs:
  include:
    - stage: Build

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;

    - stage: STG Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-gabrieladias
        on:
          branch: main

    - stage: STG TEST
      script:
        - curl https://devopslab-gabrieladias.herokuapp.com/ | grep Hello || travis_terminate 1;

    - stage: PROD Deploy
      script: skip
      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: ../labdevopscloud-gaby-e21d31214aba.json
        project: labdevopscloud-gaby
        on:
          branch: main

    - stage: PROD TEST
      script:
        - curl https://labdevopscloud-gaby.ue.r.appspot.com/ | grep Hello || travis_terminate 1;

